sudo: false
dist: trusty

language: php

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - develop
    - master
    - release-v0.1.2
    - release-v0.2.0
    - release-v0.2.1

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

# Set the global environment variables
env:
  global:
    - WP_CORE_DIR: /tmp/wordpress
  matrix:
    - PHP_VERSION=7.3 WP_VERSION=5.2.2 COVERAGE=1
    - PHP_VERSION=7.2 PHPCS=1
    - PHP_VERSION=7.2 WP_VERSION=5.2.2
    - PHP_VERSION=7.1 WP_VERSION=5.2.2
    - PHP_VERSION=7.0 WP_VERSION=5.2.2
    - PHP_VERSION=5.6 WP_VERSION=4.9
    - PHP_VERSION=5.6 WP_VERSION=5.2.2 DEBUG=1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - |
    cd $TRAVIS_BUILD_DIR
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    chmod +x wp-cli.phar
    sudo mv wp-cli.phar /usr/local/bin/wp

before_script:
  - |
    if [ ! -z "$WP_VERSION" ]; then
      # Install and config Codeception
      cp .env.dist .env
      travis_retry composer install --prefer-source --no-interaction
      if [ "$COVERAGE" == "1" ]; then
        # Install Coveralls
        mkdir -p build/logs
        COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require php-coveralls/php-coveralls
      fi
      docker-compose build \
        --build-arg DESIRED_PHP_VERSION=$(PHP_VERSION) \
        --build-arg DESIRED_WP_VERSION=$(WP_VERSION) \
        woographql
      ls -al
    fi   
  # Install PHP CodeSniffer and WPCS.
  - |
    if [ "$PHPCS" == "1" ]; then
      COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require squizlabs/php_codesniffer phpcompatibility/phpcompatibility-wp wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer
      COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-dev
      ls -al
    fi

script:
  # Execute unit tests with coverage if specified, otherwise without coverage
  - |
    if [ ! -z "$WP_VERSION" ]; then
      docker-compose run -e SUITE=functional -e COVERAGE=${COVERAGE:-0} testing --rm testing --scale app=0
      docker-compose run -e SUITE=acceptance -e COVERAGE=${COVERAGE:-0} testing --rm testing --scale app=0
      docker-compose run -e SUITE=wpunit -e COVERAGE=${COVERAGE:-0} testing --rm testing --scale app=0
    fi
  - |
    if [ "$PHPCS" == "1" ]; then
      vendor/bin/phpcs wp-graphql-woocommerce.php access-functions.php class-inflect.php includes/*.php --standard=WordPress
    fi
after_success:
  # Runs Coveralls.io client
  - |
    if [ "$COVERAGE" == "1" ]; then
      travis_retry php vendor/bin/php-coveralls -v
    fi
  
