sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master
    - develop

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

# Set the global environment variables
env:
  global:
    - WP_CORE_DIR: /tmp/wordpress
    - WP_VERSION: latest
    - COVERAGE: false

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest COVERAGE=true
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: 5.3
      env: WP_VERSION=latest
      dist: precise

install:
  - |
    cd $TRAVIS_BUILD_DIR
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    chmod +x wp-cli.phar
    sudo mv wp-cli.phar /usr/local/bin/wp

before_script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer self-update
      composer require lucatume/wp-browser:^2.2
      composer install --no-interaction
      mkdir -p build/logs
      cp tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
      cp tests/functional.suite.dist.yml tests/functional.suite.yml
      cp tests/unit.suite.dist.yml tests/unit.suite.yml
      cp tests/wpunit.suite.dist.yml tests/wpunit.suite.yml
      cp .env.dist .env
      composer install-wp-tests
      ls -al
    fi

  # Install PHP CodeSniffer and WPCS.
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer require squizlabs/php_codesniffer
      composer require dealerdirect/phpcodesniffer-composer-installer
      composer require phpcompatibility/phpcompatibility-wp
      composer require wp-coding-standards/wpcs:1.2.1
      composer require automattic/vipwpcs
      composer install

      phpenv rehash

      ./vendor/bin/phpcs --config-set default_standard WordPress
    fi

script:
 # Execute unit tests with coverage if specified, otherwise without coverage
 - |
    if [[ ! -z "$WP_VERSION" ]]; then
      if [ $COVERAGE == true ]; then
        vendor/bin/codecept run wpunit --coverage --coverage-xml
      else
        vendor/bin/codecept run wpunit
      fi
    fi
 - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      ./vendor/bin/phpcs --standard=WordPress
    fi
  
