name: build_release

on:
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    name: "Build Release"
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring, intl
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev

      - name: Remove unneeded files
        run: |
          rm -rf composer.json composer.lock tests \
          coveralls.yml netlify.toml docker docs vendor \
          bin .github .env.dist phpcs.xml .dockerignore \
          codeception.dist.yml .editorconfig .gitignore .git

      - name: List files
        run: ls -laR
