name: build_release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    name: "Build Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: mbstring, intl
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev

      - name: List files
        run: ls -laR

      - name: Generate draft release
        uses: meeDamian/github-release@2.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          draft: true
          title: "Release {{ github.ref }}"
          gzip: true
          files: >
            includes/
            vendor/
            .distignore
            access-functions.php
            CHANGELOG.md
            class-inflect.php
            LICENSE
            logo.svg
            README.md
            README.txt
            SECURITY.md
            wp-graphql-woocommerce.php
